### ISSUE TITLE
font rendering issue (Custom Font)

### ISSUE THREAD

**Issue by CaiMiao** [bayaraa/d2gl#9]
- request: configurable texture size
	- cjk thing is really large

https://github.com/bayaraa/d2gl/blob/d05ea289b6602738c704fa5c536b20bc08c044f2/d2gl/src/font.cpp#L72

- request: allow display tuning for small font
	- cjk thing is really large
![图片](https://user-images.githubusercontent.com/4640483/222858406-73112269-cb5b-4e66-a98e-537ef6f5e201.png)

**Comment by CaiMiao** [comment]
[data.csv](https://github.com/bayaraa/d2gl/files/10887041/data.csv)
![atlas](https://user-images.githubusercontent.com/4640483/222858535-89a133e5-38bd-405c-a7eb-0d93bdc87eb2.png)

**Comment by CaiMiao** [comment]
i sincirely suggest implementing realtime atlas compiler to avoid extreme large textures which might over 5k^2~10k^2 pixels...

**Comment by bayaraa** [comment]
Yeah, I used that tool to generate current atlases. It can be generated on fly but it was extremely slow even using multiple cores specially on older cpus. Thats why i use pre generated atlases.
Currently not planned to support other languages, maybe in the future.
Btw I wonder how much glyphes required in japanese d2. I don't think that all 21454 required.

**Comment by CaiMiao** [comment]
> Yeah, I used that tool to generate current atlases. It can be generated on fly but it was extremely slow even using multiple cores specially on older cpus. Thats why i use pre generated atlases. Currently not planned to support other languages, maybe in the future. Btw I wonder how much glyphes required in japanese d2. I don't think that all 21454 required.

you can't just ignore if mod creators decide to use some other ideographs... I think you can generate lower res texture on demand in another thread.

**Comment by weili0677** [comment]
> Yeah, I used that tool to generate current atlases. It can be generated on fly but it was extremely slow even using multiple cores specially on older cpus. Thats why i use pre generated atlases. Currently not planned to support other languages, maybe in the future. Btw I wonder how much glyphes required in japanese d2. I don't think that all 21454 required.

Hi,Mr.bayaraa which command you used to generated atlaes with ExocetBlizzardMedium.otf ?

**Comment by weili0677** [comment]
> @weili0677
> 
> ```
> msdf-atlas-gen.exe -font fonts/exocetblizzardot-medium.otf -type msdf -format png -imageout atlas.png -csv data.csv -charset charset.txt -size 64 -minsize 64 -dimensions 860 860 -pxrange 20
> msdf-atlas-gen.exe -font fonts/Formal436BT.ttf -type msdf -format png -imageout atlas.png -csv data.csv -charset charset.txt -size 64 -minsize 64 -dimensions 860 860 -pxrange 20
> msdf-atlas-gen.exe -font fonts/exocet-reaper-medium.ttf -type msdf -format png -imageout atlas.png -csv data.csv -charset charset.txt -size 64 -minsize 64 -dimensions 860 860 -pxrange 20
> ```
> 
> this is commands i used. inside charset.txt `[0, 255]`.

Thank you.you are very nice.

**Comment by dabeibao** [comment]
> Yeah, I used that tool to generate current atlases. It can be generated on fly but it was extremely slow even using multiple cores specially on older cpus. Thats why i use pre generated atlases. Currently not planned to support other languages, maybe in the future. Btw I wonder how much glyphes required in japanese d2. I don't think that all 21454 required.

Is it possible to generate the atlases on fly and cache them. Not sure how many glyphes will be used in Japanese; but in Chinese the frequently used characters are about 3000~5000 only.

**Comment by CaiMiao** [comment]
> Is it possible to generate the atlases on fly and cache them? Not sure how many glyphes will be used in Japanese; but in Chinese the frequently used characters are about 3000~5000 only.

I will say, forget about atlases and directly use freetype will be the best solution, 
but generate & cache on startup will be neat enough.

I have an idea to verify cache and do not generate them frequently - hashing. 
Either by collect the final language tbl loaded by game, sort unique characters as `charset.txt`, and hash it - or,
just hash digest of binary data of all language tbl together.

**Comment by bayaraa** [comment]
@CaiMiao @weili0677 @dabeibao hey guys where can i find chinese or japanese version of diablo 2?

**Comment by CaiMiao** [comment]
> @CaiMiao @weili0677 @dabeibao hey guys where can i find chinese or japanese version of diablo 2?

You can download Traditional Chinese directly in digital version on BNet, or you can find all those assets in Resurrected CASC archive.
Keep in mind that, most Chinese players use customized (modified) tbls so only including glyphs used officially may not satisfy Chinese audiences.

For Japanese version, due to licensing issue with Capcom probably, Blizz did not include them as Digital nor in Resurrected.
I'm uploading these assets which is extracted from Japanese physical release, right after installing LoD.
[CAPCOM.zip](https://github.com/bayaraa/d2gl/files/11229067/CAPCOM.zip)

**Comment by CaiMiao** [comment]
P.S. You have to create a `Use` file in `/data/local` includes the corresponding byte which you can find via below link, if you are using `-direct` to switch language.
Or you can just use that tool if you don't mind changing MPQ permanently.
https://d2mods.info/forum/viewtopic.php?f=7&t=60930

**Comment by bayaraa** [comment]
thanks.

**Comment by weili0677** [comment]
this is for 1.13c
https://drive.google.com/file/d/1jZCAJRu77BgFQs8TXC7TtjCnnOSMC7Rt/view?usp=sharing

this is for 1.14d
https://drive.google.com/file/d/17boLX3Io3tUdXiHWBquvjOydtAtolM5m/view?usp=sharing

**Comment by bayaraa** [comment]
@weili0677 @CaiMiao @dabeibao hello all!
finally i am working other language support.
if it's not much trouble, could you translate these text to chinese (if possible japanese also)?
```yaml
exit.dc6: "SAVE AND EXIT GAME"
returntogame.dc6: "RETURN TO GAME"
previous.dc6: "PREVIOUS MENU"
sprevious.dc6: "PREVIOUS MENU"
smallon.dc6: "ON"
smalloff.dc6: "OFF"
smallyes.dc6: "YES"
smallno.dc6: "NO"
soundoptions.dc6: "SOUND OPTIONS"
sound.dc6: "SOUND"
music.dc6: "MUSIC"
3dsound.dc6: "3D SOUND"
eax.dc6: "ENVIRONMENTAL EFFECTS"
3dbias.dc6: "3D BIAS"
npcspeech.dc6: "NPC SPEECH"
audiotext.dc6: "AUDIO AND TEXT"
audioonly.dc6: "AUDIO ONLY"
textonly.dc6: "TEXT ONLY"
videooptions.dc6: "VIDEO OPTIONS"
resolution.dc6: "RESOLUTION"
lightquality.dc6: "LIGHTING QUALITY"
high.dc6: "HIGH"
medium.dc6: "MEDIUM"
low.dc6: "LOW"
blendshadow.dc6: "BLENDED SHADOWS"
perspective.dc6: "PERSPECTIVE"
gamma.dc6: "GAMMA"
contrast.dc6: "CONTRAST"
automapoptions.dc6: "AUTOMAP OPTIONS"
automapmode.dc6: "AUTOMAP SIZE"
full.dc6: "FULL SCREEN"
mini.dc6: "MINI MAP"
automapfade.dc6: "FADE"
everything.dc6: "EVERYTHING"
center.dc6: "CENTER"
auto.dc6: "AUTO"
automapcenter.dc6: "CENTER WHEN CLEARED"
automapparty.dc6: "SHOW PARTY"
automappartynames.dc6: "SHOW NAMES"
cfgoptions.dc6: "CONFIGURE CONTROLS"
```

**Comment by weili0677** [comment]
> @weili0677 @CaiMiao @dabeibao hello all! finally i am working other language support. if it's not much trouble, could you translate these text to chinese (if possible japanese also)?
> 
> ```yaml
> exit.dc6: "SAVE AND EXIT GAME"
> returntogame.dc6: "RETURN TO GAME"
> previous.dc6: "PREVIOUS MENU"
> sprevious.dc6: "PREVIOUS MENU"
> smallon.dc6: "ON"
> smalloff.dc6: "OFF"
> smallyes.dc6: "YES"
> smallno.dc6: "NO"
> soundoptions.dc6: "SOUND OPTIONS"
> sound.dc6: "SOUND"
> music.dc6: "MUSIC"
> 3dsound.dc6: "3D SOUND"
> eax.dc6: "ENVIRONMENTAL EFFECTS"
> 3dbias.dc6: "3D BIAS"
> npcspeech.dc6: "NPC SPEECH"
> audiotext.dc6: "AUDIO AND TEXT"
> audioonly.dc6: "AUDIO ONLY"
> textonly.dc6: "TEXT ONLY"
> videooptions.dc6: "VIDEO OPTIONS"
> resolution.dc6: "RESOLUTION"
> lightquality.dc6: "LIGHTING QUALITY"
> high.dc6: "HIGH"
> medium.dc6: "MEDIUM"
> low.dc6: "LOW"
> blendshadow.dc6: "BLENDED SHADOWS"
> perspective.dc6: "PERSPECTIVE"
> gamma.dc6: "GAMMA"
> contrast.dc6: "CONTRAST"
> automapoptions.dc6: "AUTOMAP OPTIONS"
> automapmode.dc6: "AUTOMAP SIZE"
> full.dc6: "FULL SCREEN"
> mini.dc6: "MINI MAP"
> automapfade.dc6: "FADE"
> everything.dc6: "EVERYTHING"
> center.dc6: "CENTER"
> auto.dc6: "AUTO"
> automapcenter.dc6: "CENTER WHEN CLEARED"
> automapparty.dc6: "SHOW PARTY"
> automappartynames.dc6: "SHOW NAMES"
> cfgoptions.dc6: "CONFIGURE CONTROLS"
> ```

```
exit.dc6: "储存并退出游戏"
returntogame.dc6: "返回游戏"
previous.dc6: "前一菜单"
sprevious.dc6: "前一菜单"
smallon.dc6: "开"
smalloff.dc6: "关"
smallyes.dc6: "是"
smallno.dc6: "否"
soundoptions.dc6: "声音选项"
sound.dc6: "声音"
music.dc6: "音乐"
3dsound.dc6: "3D音效"
eax.dc6: "环场效果"
3dbias.dc6: "3D偏向"
npcspeech.dc6: "NPC语音"
audiotext.dc6: "语音和文字"
audioonly.dc6: "仅有语音"
textonly.dc6: "仅有文字"
videooptions.dc6: "影像选项"
resolution.dc6: "分辨率"
lightquality.dc6: "打光品质"
high.dc6: "高"
medium.dc6: "中"
low.dc6: "低"
blendshadow.dc6: "混合影子"
perspective.dc6: "透视"
gamma.dc6: "亮度"
contrast.dc6: "对比度"
automapoptions.dc6: "自动地图选项"
automapmode.dc6: "自动地图大小"
full.dc6: "全屏"
mini.dc6: "小型地图"
automapfade.dc6: "淡化"
everything.dc6: "所有"
center.dc6: "中间"
auto.dc6: "自动"
automapcenter.dc6: "清除时置中"
automapparty.dc6: "显示队伍"
automappartynames.dc6: "显示名称"
cfgoptions.dc6: "设定控制"
```

**Comment by bayaraa** [comment]
@weili0677 thanks!
sorry forgot these 3 🙏 
```yaml
youdiedhardcore.dc6: "You have died"
youdiedinst.dc6: "Press ESC to continue."
youdiedsoftcore.dc6: "You lost gold"
```
